language: go

go:
  - 1.4.2

go_import_path: go.bug.st/serial

env:
  - TEST_OS=linux TEST_ARCH=386
  - TEST_OS=linux TEST_ARCH=amd64
  - TEST_OS=linux TEST_ARCH=arm
  - TEST_OS=windows TEST_ARCH=386
  - TEST_OS=windows TEST_ARCH=amd64
  - TEST_OS=darwin TEST_ARCH=386
  - TEST_OS=darwin TEST_ARCH=amd64
  - TEST_OS=freebsd TEST_ARCH=amd64
  - TEST_OS=dragonfly TEST_ARCH=amd64

matrix:
  allow_failures:
    - env: TEST_OS=freebsd TEST_ARCH=amd64
    - env: TEST_OS=dragonfly TEST_ARCH=amd64

before_install:
# bootstrap go tools for the specific OS/Arch
  - ( cd $GOROOT/src; GOOS=$TEST_OS GOARCH=$TEST_ARCH ./make.bash )

script:
  - GOARM=5 GO386=387 GOOS=$TEST_OS GOARCH=$TEST_ARCH go build -v ./...
  - GOARM=5 GO386=387 GOOS=$TEST_OS GOARCH=$TEST_ARCH go test -c -v ./...

notifications:
  email:
    recipients:
      - c.maglie@bug.st
    on_success: change
    on_failure: always

